license = ''   #授权码
listen_port = 1234  #选一个自己喜欢的数字做监听端口
#outbound = 'eth0'  #当有双网卡时需要打开此选项，指定公网IP所在的网卡

#端口段转发，多个复制整段黏贴即可
[[range]]
port = '1-1000'
remote_addr = '127.0.0.1'
remote_port = '1-1000'

#单个端口转发，多个复制整段黏贴即可
[[single]]
port = 1234
remote_addr = '127.0.0.1'
remote_port = 1234